server:
  port: 0



spring:  
  application:
   name: Login-Service  
   
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true
   
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   



pivotal:
  employeeservice:
       name: Employee-Service